Update es-ES.properties
arlogn/easyshare pull request #13
Opened 2016-11-16 20:03 UTC by elKaZe

Updated, completed, and corrected ;)

2016-11-17 00:38 UTC, arlogn requested changes
Good, thanks. I've left a comment about a little error that should be fixed before to merge the pull request.

2016-11-17 00:38 UTC, arlogn commented on locale/es-ES.properties
> +errorNoToken = errorNoToken = Imposible obtener el token de autentificación. \nRevisá la URL del Pod.
The identifier is duplicated

2016-11-22 20:29 UTC, elKaZe commented
done, sorry I've pasted this text en libreoffice to check the accents, I think that i made a mistake

2016-11-24 21:44 UTC, arlogn approved these changes

2016-11-24 21:44 UTC, merged

2016-11-24 21:44 UTC, arlogn commented
Thank you.